### PR TITLE
Athena CWL

### PR DESCRIPTION
**Pull request by buehlere**
✔️  working athena workflow 
✔️ relies on recent pull request to [commandlinetools](https://github.com/msk-access/cwl-commandlinetools/pull/153) 
✔️ conditionals to skip steps if inputs are missing

### CODE REVIEW

**Review by rhshah — CHANGES_REQUESTED** [review]
Thanks, @buehlere  can we add the README and link it here https://github.com/msk-access/cwl_subworkflows/blob/master/docs/SUMMARY.md @carmelinacharalambous  can you please check if intended output is obtained and all looks good

**Comment by rhshah** [comment]
@buehlere  we also need to update GitHub workflows, can you modify these to the version of toil you used for testing 

- [ ]  https://github.com/msk-access/cwl_subworkflows/blob/e7899a449ad41fb7c48e16cf0415dcbc808ef01f/.github/workflows/validate_cwls.yml#L26

- [ ] https://github.com/msk-access/cwl_subworkflows/blob/e7899a449ad41fb7c48e16cf0415dcbc808ef01f/.github/workflows/pack_cwls.yml#L28

**Review by rhshah — COMMENTED** [review]
Do we need PickUpValue option?

**Comment by rhshah** [comment]
Can you also change pip in `requirements.txt` to `pip==21.1`

**Comment by buehlere** [comment]
> Can you also change pip in `requirements.txt` to `pip==21.1` @buehlere

I've updated with this [119c7c3](https://github.com/msk-access/cwl_subworkflows/pull/174/commits/119c7c3de3bd51e49cbb08297d6706061066f47e)! I also updated docs and github actions. 

I'm a little unfamiliar with a PickUpValue option?

**Comment by rhshah** [comment]
> > Can you also change pip in `requirements.txt` to `pip==21.1` @buehlere
> 
> I've updated with this [119c7c3](https://github.com/msk-access/cwl_subworkflows/pull/174/commits/119c7c3de3bd51e49cbb08297d6706061066f47e)! I also updated docs and github actions.
> 
> I'm a little unfamiliar with a PickUpValue option?

its for picking output value when you are skipping steps. we might need it either here or top workflow calling it

**Comment by rhshah** [comment]
@buehlere  we probably need to update the commandlinetools branch

**Pull request merged**
